CREATE SEQUENCE SEQ_PROPOSTA_CREDITO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLIENTE_PROPOSTA_CREDITO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TELEFONE_PROPOSTA_CREDITO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ENDERECO_PROPOSTA_CREDITO START WITH 1 INCREMENT BY 1 NOCACHE;


CREATE TABLE ENDERECO_PROPOSTA_CREDITO(
   ID NUMBER,
   endereco VARCHAR2(400),
   numero NUMBER,
   complemento VARCHAR2(50),
   cep VARCHAR2(8),
   bairro VARCHAR2(250),
   cidade VARCHAR2(250),
   uf VARCHAR2(2),
   CONSTRAINT END_PROP_CREDITO_PK PRIMARY KEY(ID)
   );
 
CREATE TABLE TELEFONE_PROPOSTA_CREDITO(
  id NUMBER,
  tipo CHAR(1),
  numero VARCHAR2(9),
  ddd VARCHAR2(2),
  CONSTRAINT TELEFONE_PROP_CREDITO_PK PRIMARY KEY(ID),
  CONSTRAINT TEL_CLI_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE_PROPOSTA_CREDITO(ID)
)

CREATE TABLE CLIENTE_PROPOSTA_CREDITO(
  id NUMBER,
  nome VARCHAR2(400),
  cpf VARCHAR2(11),
  rg VARCHAR2(14),
  data_Nascimento VARCHAR2(10),
  ID_ENDERECO NUMBER,
  CONSTRAINT CLIENTE_PROP_CREDITO_PK PRIMARY KEY(ID),
  CONSTRAINT CLI_END_FK FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO_PROPOSTA_CREDITO(ID)
)

CREATE TABLE PROPOSTA_CREDITO(
 id NUMBER,
 produto VARCHAR2(50),
 valor NUMBER,
 status VARCHAR(20),
 id_cliente NUMBER,
 CONSTRAINT PROPOSTA_CREDITO_PK PRIMARY KEY(ID),
 CONSTRAINT P_CREDITO_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE_PROPOSTA_CREDITO(ID)
)