--DECODE
SELECT * FROM EMPLOYEES WHERE JOB_ID IS NOT NULL;
SELECT FIRST_NAME, LAST_NAME, JOB_ID, 
    DECODE(JOB_ID, 'IT_PROG', 'PROGRAMADOR', 
    'AD_VP', 'VP',
    'FI_ACCOUNT', 'ACCOUNT',
    'PU_CLERK', 'CLERK',
    'N/A') AS CARGO 
FROM EMPLOYEES WHERE JOB_ID IS NOT NULL ;

--NVL
SELECT FIRST_NAME, LAST_NAME, JOB_ID, COMMISSION_PCT AS COMISSAO FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME, JOB_ID, NVL(COMMISSION_PCT, 0) AS COMISSAO FROM EMPLOYEES;

--NVL2
SELECT FIRST_NAME, LAST_NAME, JOB_ID, MANAGER_ID AS ID_MANAGER FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME, JOB_ID, NVL2(MANAGER_ID, 'IDENTIFICADOR_GERENCIA', 'N/A') AS ID_MANAGER FROM EMPLOYEES;

--LPAD
SELECT * FROM CADASTRO_PESSOA WHERE id = 3; 
SELECT NOME, LPAD(CPF, 11, '0') AS CPF  FROM CADASTRO_PESSOA WHERE id = 3;

--RPAD
SELECT NOME, RPAD(CPF, 11, '0') AS CPF  FROM CADASTRO_PESSOA WHERE id = 3;


--LAST_DAY
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;
SELECT  LAST_DAY(SYSDATE) AS ULTIMO_DIA FROM DUAL;
SELECT LAST_DAY(HIRE_DATE) ULTIMA_DATA_CONTRATACAO FROM EMPLOYEES WHERE DEPARTMENT_ID = 90; 

--PRIMEIRO DIA DO MES
SELECT TRUNC(SYSDATE, 'mm') AS PRIMEIRO_DIA_MES FROM DUAL;
SELECT TRUNC(TO_DATE('20/01/2024', 'DD/MM/YYYY'), 'mm') AS PRIMEIRO_DIA_MES FROM DUAL;