CREATE OR REPLACE PACKAGE PCK_PROPOSTA_CREDITO IS

PROCEDURE PRC_CRIA_PROPOSTA(P_PROPOSTA IN PROPOSTA_CREDITO_TYPE);
PROCEDURE PRC_POPULA_ENDERECO(P_ENDERECO IN ENDERECO_PROPOSTA_CREDITO_TYPE);
PROCEDURE PRC_POPULA_CLIENTE(P_CLIENTE IN CLIENTE_PROPOSTA_CREDITO_TYPE, V_SQL_CODE OUT NUMBER, V_SQL_ERROR OUT VARCHAR2);
PROCEDURE PRC_POPULA_TELEFONE(P_TELEFONES IN TELEFONE_PROPOSTA_CREDITO_TYPE_TABLE, ID_CLIENTE IN NUMBER, V_SQL_CODE OUT NUMBER, V_SQL_ERROR OUT VARCHAR2);
PROCEDURE PRC_POPULA_PROPOSTA(P_PROPOSTA IN PROPOSTA_CREDITO_TYPE, V_SQL_CODE OUT NUMBER, V_SQL_ERROR OUT VARCHAR2);

END PCK_PROPOSTA_CREDITO;